//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDisasterPreventionInformationApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalDisasterPreventionInformationApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   商品登録→ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_AddProduct {
            get {
                return ResourceManager.GetString("Btn_AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Confirm {
            get {
                return ResourceManager.GetString("Btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   破棄 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Discard {
            get {
                return ResourceManager.GetString("Btn_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Btn_Register {
            get {
                return ResourceManager.GetString("Btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地震ハザードマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hazard_Earthquake {
            get {
                return ResourceManager.GetString("Hazard_Earthquake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   土砂・洪水ハザードマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hazard_FloodLandslide {
            get {
                return ResourceManager.GetString("Hazard_FloodLandslide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   津波ハザードマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hazard_Tsunami {
            get {
                return ResourceManager.GetString("Hazard_Tsunami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域防災情報アプリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_AppTitle {
            get {
                return ResourceManager.GetString("Header_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_Font {
            get {
                return ResourceManager.GetString("Header_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハザードマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_HazardMap {
            get {
                return ResourceManager.GetString("Header_HazardMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_MyPage {
            get {
                return ResourceManager.GetString("Header_MyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ルート検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_RouteSearch {
            get {
                return ResourceManager.GetString("Header_RouteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備蓄管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_Stock {
            get {
                return ResourceManager.GetString("Header_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Header_Top {
            get {
                return ResourceManager.GetString("Header_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハザードマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_HazardMap {
            get {
                return ResourceManager.GetString("Menu_HazardMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備蓄管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Stock {
            get {
                return ResourceManager.GetString("Menu_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Top {
            get {
                return ResourceManager.GetString("Menu_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番地 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Address {
            get {
                return ResourceManager.GetString("Reg_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_AddressType {
            get {
                return ResourceManager.GetString("Reg_AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_AutoFill {
            get {
                return ResourceManager.GetString("Reg_AutoFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号から自動入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_AutoFromZip {
            get {
                return ResourceManager.GetString("Reg_AutoFromZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   建物名・部屋番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Building {
            get {
                return ResourceManager.GetString("Reg_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   市区町村 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_City {
            get {
                return ResourceManager.GetString("Reg_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の内容でよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Confirm {
            get {
                return ResourceManager.GetString("Reg_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Email {
            get {
                return ResourceManager.GetString("Reg_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未入力です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Empty {
            get {
                return ResourceManager.GetString("Reg_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フリガナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Furigana {
            get {
                return ResourceManager.GetString("Reg_Furigana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カタカナで入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_FuriganaHint {
            get {
                return ResourceManager.GetString("Reg_FuriganaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フリガナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_FuriganaLabel {
            get {
                return ResourceManager.GetString("Reg_FuriganaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   氏名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Name {
            get {
                return ResourceManager.GetString("Reg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   任意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Optional {
            get {
                return ResourceManager.GetString("Reg_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号（ハイフンなし） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Phone {
            get {
                return ResourceManager.GetString("Reg_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   都道府県 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Prefecture {
            get {
                return ResourceManager.GetString("Reg_Prefecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   町域 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Town {
            get {
                return ResourceManager.GetString("Reg_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   地域防災情報アプリへようこそ！会員情報のご登録をお願いします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Welcome {
            get {
                return ResourceManager.GetString("Reg_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号（7桁） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reg_Zip {
            get {
                return ResourceManager.GetString("Reg_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_Category {
            get {
                return ResourceManager.GetString("Stock_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリ別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_CategoryOrder {
            get {
                return ResourceManager.GetString("Stock_CategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_Delete {
            get {
                return ResourceManager.GetString("Stock_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費期限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_Expire {
            get {
                return ResourceManager.GetString("Stock_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消費期限順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_ExpireOrder {
            get {
                return ResourceManager.GetString("Stock_ExpireOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品名別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_NameOrder {
            get {
                return ResourceManager.GetString("Stock_NameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_Others {
            get {
                return ResourceManager.GetString("Stock_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_ProductName {
            get {
                return ResourceManager.GetString("Stock_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_Quantity {
            get {
                return ResourceManager.GetString("Stock_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並べ替え に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock_Sort {
            get {
                return ResourceManager.GetString("Stock_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   避難所リスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Top_ShelterList {
            get {
                return ResourceManager.GetString("Top_ShelterList", resourceCulture);
            }
        }
    }
}
